/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoodooRouteImport } from './routes/voodoo'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as CompetitiveRouteImport } from './routes/competitive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdIdRouteImport } from './routes/ad.$id'

const VoodooRoute = VoodooRouteImport.update({
  id: '/voodoo',
  path: '/voodoo',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitiveRoute = CompetitiveRouteImport.update({
  id: '/competitive',
  path: '/competitive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdIdRoute = AdIdRouteImport.update({
  id: '/ad/$id',
  path: '/ad/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitive': typeof CompetitiveRoute
  '/geo': typeof GeoRoute
  '/insights': typeof InsightsRoute
  '/performance': typeof PerformanceRoute
  '/voodoo': typeof VoodooRoute
  '/ad/$id': typeof AdIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitive': typeof CompetitiveRoute
  '/geo': typeof GeoRoute
  '/insights': typeof InsightsRoute
  '/performance': typeof PerformanceRoute
  '/voodoo': typeof VoodooRoute
  '/ad/$id': typeof AdIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competitive': typeof CompetitiveRoute
  '/geo': typeof GeoRoute
  '/insights': typeof InsightsRoute
  '/performance': typeof PerformanceRoute
  '/voodoo': typeof VoodooRoute
  '/ad/$id': typeof AdIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competitive'
    | '/geo'
    | '/insights'
    | '/performance'
    | '/voodoo'
    | '/ad/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competitive'
    | '/geo'
    | '/insights'
    | '/performance'
    | '/voodoo'
    | '/ad/$id'
  id:
    | '__root__'
    | '/'
    | '/competitive'
    | '/geo'
    | '/insights'
    | '/performance'
    | '/voodoo'
    | '/ad/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitiveRoute: typeof CompetitiveRoute
  GeoRoute: typeof GeoRoute
  InsightsRoute: typeof InsightsRoute
  PerformanceRoute: typeof PerformanceRoute
  VoodooRoute: typeof VoodooRoute
  AdIdRoute: typeof AdIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voodoo': {
      id: '/voodoo'
      path: '/voodoo'
      fullPath: '/voodoo'
      preLoaderRoute: typeof VoodooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitive': {
      id: '/competitive'
      path: '/competitive'
      fullPath: '/competitive'
      preLoaderRoute: typeof CompetitiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad/$id': {
      id: '/ad/$id'
      path: '/ad/$id'
      fullPath: '/ad/$id'
      preLoaderRoute: typeof AdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitiveRoute: CompetitiveRoute,
  GeoRoute: GeoRoute,
  InsightsRoute: InsightsRoute,
  PerformanceRoute: PerformanceRoute,
  VoodooRoute: VoodooRoute,
  AdIdRoute: AdIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
